# Generated by Django 3.1.2 on 2020-10-13 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(max_length=25)),
                ('droga', models.CharField(max_length=25)),
                ('obraSocial', models.CharField(max_length=25)),
                ('plan', models.CharField(max_length=25)),
                ('importe', models.FloatField(default=0)),
                ('fechaHoraVenta', models.DateTimeField()),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.farmacia')),
            ],
        ),
    ]
