# Generated by Django 3.1.2 on 2020-10-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='farmacia',
        ),
        migrations.DeleteModel(
            name='Farmacia',
        ),
    ]
